apiVersion: batch/v1
kind: CronJob
metadata:
  name: forbid-cron
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: Forbid 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: busybox-container
            image: busybox
            command: ["/bin/sh"]
            args: ["-c", "echo sleeping...; sleep 150"]
          restartPolicy: OnFailure

