apiVersion: v1
kind: Secret 
metadata:
  name: super-secret 
type: Opaque
stringData:
  api_key: sk-test-4f8a9c2b7d3e1f6a5b8c9d0e2f3a4b5c6d7e8f9a0b1c2d
  auth_token: yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNzU4MzkyIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzQzODk2MDAwfQ.k7X9mQ2vL8pR3tY6wN4jB1cF5dG8hJ0lM2nP9qS4uV7x
  encryption_key: jzp8my4dT2oLXI6dLzp7HE1ujwKjPNfqPxK3x9PpDyo=
