apiVersion: batch/v1
kind: CronJob
metadata:
  name: system-info-cron
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: busybox-container
            image: busybox
            command:
            - sh 
            - -c 
            - | 
              echo "Time: $(date)"
              echo "Host: $(hostname)"
              echo
              echo "Process: $(ps aux | wc -l)"
          restartPolicy: OnFailure


