apiVersion: apps/v1
kind: Deployment
metadata:
  name: liveness-http
spec:
  selector:
    matchLabels:
      app: liveness-http
  template:
    metadata:
      labels:
        app: liveness-http
    spec:
      containers:
      - name: liveness-http
        image: nginx:1.25
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
            httpHeaders:
            - name: custom-header
              value: health-check
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
   
