apiVersion: v1
kind: Service
metadata:
  name: frontend-service 
  labels:
    environment: production
spec:
  selector:
    app: prod-frontend 
  type: ClusterIP
  ports:
  - name: frontend-service 
    protocol: TCP
    port: 80
    targetPort: 80
