apiVersion: batch/v1
kind: Job 
metadata:
  name: fault-tolerant-job 
spec:
  backoffLimit: 4 
  template:
    spec:
      containers:   
      - name: busybox-container 
        image: busybox 
        command:
        - sh 
        - -c 
        - |
          if [ $((RANDOM % 2)) -eq 0 ]; then 
            exit 0
          else 
            exit 1
          fi
      restartPolicy: OnFailure
