apiVersion: v1 
kind: Pod 
metadata:
  name: secret-pod 
spec:
  containers:
  - name: nginx-container 
    image: nginx 
    env: 
    - name: DB_HOST
      valueFrom: 
        configMapKeyRef: 
          name: app-config 
          key: database.host

    - name: DB_PAsSWORD 
      valueFrom:
        secretKeyRef: 
          name: app-secret 
          key: database.password  
