apiVersion: apps/v1
kind: Deployment 
metadata:
  name: multi-service-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multi-service-app
  template:
    metadata:
      labels:
        app: multi-service-app
    spec:
      containers:
      - name: frontend
        image: nginx:1.25
        ports:
        - containerPort: 80

      - name: backend
        image: httpd:2.4 
        ports:
        - containerPort: 8080
        command:  ["/bin/sh"]
        args:
          - "-c"
          - |
            cp /usr/local/apache2/conf/httpd.conf /usr/local/apache2/conf/httpd-custom.conf && \
            sed -i 's/^Listen 80/Listen 8080/g' /usr/local/apache2/conf/httpd-custom.conf && \
            sed -i 's/^#ServerName www.example.com:80/ServerName localhost:8080/g' \
              /usr/local/apache2/conf/httpd-custom.conf
            echo "<h1>Apache server working on port 8080</h1>" > \
              /usr/local/apache2/htdocs/index.html && \
            echo "<p>Pod: $(hostname)</p>" >> /usr/local/apache2/htdocs/index.html && \
            httpd -f /usr/local/apache2/conf/httpd-custom.conf -DFOREGROUND
