apiVersion: apps/v1
kind: Deployment 
metadata:
  name: web-app
  labels:
    app: web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app 
        environment: test
    spec:
      containers:
      - name: apache-api
        image: httpd:2.4-alpine
        ports:
        - containerPort: 8080
        command: ["/bin/sh"]
        args:
          - "-c"
          - |
            cp /usr/local/apache2/conf/httpd.conf /usr/local/apache2/conf/httpd-custom.conf && \
            sed -i 's/^Listen 80/Listen 8080/g' /usr/local/apache2/conf/httpd-custom.conf && \
            sed -i 's/^#ServerName www.example.com:80/ServerName localhost:8080/g' \
              /usr/local/apache2/conf/httpd-custom.conf
            echo "<h1>Apache server working on port 8080</h1>" > \
              /usr/local/apache2/htdocs/index.html && \
            echo "<p>Pod: $(hostname)</p>" >> /usr/local/apache2/htdocs/index.html && \
            httpd -f /usr/local/apache2/conf/httpd-custom.conf -DFOREGROUND
