apiVersion: v1
kind: Service 
metadata:
  name: failure-service 
spec:
  type: ClusterIP
  selector:
    app: non-existent
  ports:
  - name: nginx-port
    protocol: TCP
    port: 80
    targetPort: 80
