apiVersion: v1
kind: Pod 
metadata:
  name: app-config-pod 
spec:
  containers: 
  - name: nginx-container
    image: nginx 
    
    volumeMounts:
    - name: app-config-volume 
      mountPath: /etc/app/config/application.properties
      subPath: application.properties

    - name: security-volume 
      mountPath: /app/security/security.key 
      subPath: security.key

  volumes: 
  - name: app-config-volume
    secret: 
      secretName: app-config-secret 
      items:
      - key: application.properties
        path: application.properties
      defaultMode: 0644 

  - name: security-volume 
    secret: 
      secretName: app-config-secret
      items:
      - key: security.key 
        path: security.key 
      defaultMode: 0400
