apiVersion: v1
kind: Pod 
metadata:
  name: web-pod 
spec:
  containers: 
  - name: test-container
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "sleep 3600"]
    env:
    - name: COLOR
      valueFrom:
        configMapKeyRef:
          name: web-config 
          key: APP_COLOR
    - name: APP_ENV
      valueFrom: 
        configMapKeyRef: 
          name: web-config 
          key: APP_ENV
