apiVersion: batch/v1 
kind: Job 
metadata:
  name: batch-processor 
spec:
  completions: 8
  parallelism: 2
  template:
    spec: 
      containers:
      - name: worker 
        image: busybox 
        command:
        - sh 
        - -c 
        - |
          echo "id: $HOSTNAME"; sleep 2
      restartPolicy: Never
