apiVersion: batch/v1
kind: CronJob 
metadata:
  name: sequntial-processor-cron 
spec:
  schedule: "*/4 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      completions: 4 
      parallelism: 1 
      template: 
        spec:
          containers:
          - name: busybox-container 
            image: busybox 
            command: ["/bin/sh"]
            args: ["-c", "echo Processing item $((RANDOM % 100)); sleep 30"]
          restartPolicy: OnFailure




