apiVersion: v1
kind: Pod
metadata:
  name: app-2
  labels:
    env: prod
    app: main
    tier: frontend
    owner: user
spec: 
  containers:
  - name: container-hello
    image: nginx:latest
    ports:
      - containerPort: 80

  - name: container-tomcat
    image: tomcat:8.5.38
    ports:
      - containerPort: 8080
