apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app-statefulset 
spec:
  updateStrategy: 
    type: RollingUpdate
    rollingUpdate:
      partition: 3
  selector:
    matchLabels:
      app: app-pod
  serviceName: "app-statefulset"
  replicas: 6 
  template:
    metadata:
      labels:
        app: app-pod 
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 80
          name: app-statefulset 
        volumeMounts:
        - name: www
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi

