apiVersion: v1
kind: Pod
metadata:
  name: configmap-env-prod
spec:
  containers:
  - name: test-container
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "sleep 3600"]
    env: 
    - name: DB_HOST
      valueFrom:
        configMapKeyRef:
          name: app-config 
          key: DATABASE_HOST
    - name: DB_PORT
      valueFrom:
        configMapKeyRef:
          name: app-config 
          key: DATABASE_PORT

