apiVersion: apps/v1
kind: Deployment 
metadata:
  name: recreate-app
spec:
  replicas: 3
  strategy: 
    type: Recreate 
  selector:
    matchLabels:
      app: recreate-app
  template:
    metadata:
      labels:
        app: recreate-app
    spec:
      containers:
      - name: app-container
        image: httpd:2.4 
        ports:
        - containerPort: 80
