apiVersion: v1
kind: Pod 
metadata:
  name: failure-pod 
spec:
  containers:
  - name: nginx-container
    image: nginx 
    env:
    - name: mysecret
      valueFrom:
        secretKeyRef:
          name: secret-secret
          key: topsecret 

